// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetArticleContent(arg1:string):Promise<string>;

export function GetArticleImage(arg1:string):Promise<string>;

export function GetRSS(arg1:string):Promise<Array<main.Item>>;

export function IsPremium(arg1:string):Promise<boolean>;
