// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetArticleContent(arg1) {
  return window['go']['main']['App']['GetArticleContent'](arg1);
}

export function GetArticleImage(arg1) {
  return window['go']['main']['App']['GetArticleImage'](arg1);
}

export function GetRSS(arg1) {
  return window['go']['main']['App']['GetRSS'](arg1);
}
